### PR TITLE
Add the new episode URI formats

### PR DESCRIPTION
**Pull request by shem8**
Looks like Spotify added new URI for Podcasts, so adding support for those.

### CODE REVIEW

**Comment by Kikobeats** [comment]
Thanks for this!

LGTM, waiting if @TooTallNate has any objection, otherwise it will land soon 🙂

**Comment by shem8** [comment]
Hey @Kikobeats , can you release a new version with this fix please?

**Comment by Kikobeats** [comment]
@shem8 

I don't have npm publication permissions

```bash
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/spotify-uri - You do not have permission to publish "spotify-uri". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```

@TooTallNate can you please release a new minor version or giving me permission for publishing it?

**Comment by Kikobeats** [comment]
published `spotify-uri@2.1.0` 🎉

**Comment by TooTallNate** [comment]
@Kikobeats can you push the tag?

**Comment by TooTallNate** [comment]
Oh nvm, I see it's there. Can you run `npx release` to generate a GitHub Release?

**Pull request merged**
