### PR TITLE
Fix non-user playlist URI formatting

### PR DESCRIPTION
**Pull request by miraclx**
Addressing issue #6 
Add support for a user or non-user playlist by checking if the user property is defined.
Omitting if not defined.

### CODE REVIEW

**Comment by TooTallNate** [comment]
LGTM. Can you add a test case please?

**Comment by TooTallNate** [comment]
Also, probably need to fix the logic in `formatOpenURL.js` as well, right?

**Comment by miraclx** [comment]
Done and done.

**Comment by TooTallNate** [comment]
Looks great, thank you!

**Pull request merged**
